import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
import Header from "./components/header/header";
import Footer from "./components/footer";
import StickyHeaderWrapper from "./components/header/StickyHeaderWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <StickyHeaderWrapper>
            <Header />
          </StickyHeaderWrapper>
          <main className="min-h-screen"> {children} </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
